### ISSUE TITLE
Typing effect shifts text

### ISSUE THREAD

**Issue by borisnezlobin** [BostonRohan/gen-z-writes#21]
https://github.com/BostonRohan/gen-z-writes/assets/146669165/2f3db980-74cd-4db5-814c-7192605611f3

might be better to just not have a typing effect there (the text doesn't change). If you really want a typing effect there, you might want to cycle through different strings (i.e., "literary changemakers", "future leaders", and so on and so forth), have a fixed starting point (see the issue in the video), and maybe a smaller delay between typed letters.

**Comment by BostonRohan** [comment]
ended up just getting rid of the effect. thanks again! @borisnezlobin [#22]

**Comment by borisnezlobin** [comment]
aw.. I liked it! was there no way of fixing it in another way? if you want, I could try and take a look

**Comment by BostonRohan** [comment]
@borisnezlobin I liked the idea that you had of flipping between different adjectives, I'll see if I can find an example of something like that.

**Comment by borisnezlobin** [comment]
There's something similar on [StackOverflow's homepage](https://stackoverflow.com/), but it's not adjectives or a typing effect.

**Comment by BostonRohan** [comment]
@borisnezlobin Finally got around to this. Thanks again! https://github.com/BostonRohan/gen-z-writes/pull/40
